title: From the Field Desk of C. M. Helmer
description: "Personal website of C. M. Helmer re: missiology, technology, bibliology."
author: C. M. Helmer

email: desk@cmhelmer.com
microblog: cmhlmr
twitter: cmhlmr
github: cmhlmr

url: https://cmhelmer.com

# analytics: UA-XXXXX-Y

# See https://developers.google.com/maps/documentation/static-maps/
google_static_maps: AIzaSyC4L16R7aBCbJcmz4ukMpMKwNOpK0azZ4Y

# See https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Kolkata

date_format: "%b %-d, %Y"

title_separator: "⁃"

excerpt_separator: "

"
excerpt_length: 140

content_filters:
- wiki
- mark
- figure

permalink: /:collection/:slug

include: ["_pages"]

collections:
  notes:
    title: "Notes"
    order: 1
#   color: "#a6565e" # thematic color
    output: true
  ctbp:
    title: "CTBP"
    order: 2
    output: true
  lifted:
    title: "Lifted"
    order: 3
    output: true
  nepali:
    title: "Nepali"
    order: 4
    output: true
  crossroads:
    title: "Crossroads"
    order: 5
    output: true

defaults:
- scope:
    path: "media"
  values:
    attachment: true # show these static files in attachments layout (default to false)
- scope:
    path: "_notes"
  values:
    layout: note
- scope:
    path: "_ctbp"
  values:
    layout: note
- scope:
    path: "_lifted"
  values:
    layout: note
- scope:
    path: "_nepali"
  values:
    layout: note
- scope:
    path: "_crossroads"
  values:
    layout: note
# Jekyll 3.7
# - scope:
#     path: "*/index.html"
#   values:
#     layout: "contents"
# - scope:
#     path: "*/tags.html"
#   values:
#     layout: "tags"
# - scope:
#     path: "*/feed.xml"
#   values:
#     layout: "feed"

sass:
  style: compressed

kramdown:
  parse_block_html: true

# Plugins:

# Not jekyll-feed:
feed:
- title: ""
  url: /feed.xml
- title: "Micro Blog"
  url: /posts/feed.xml

# jekyll-seo-tag:
webmaster_verifications:
#  alexa:
  bing: 623ED864F6E47AE258E006DCC84DB67D
#  google:
#  yandex:

# jekyll-titles-from-headings:
titles_from_headings:
  strip_title: true
  collections: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-default-layout
- jekyll-titles-from-headings
# - jemoji
# - jekyll-feed
# - jekyll-paginate
# - jekyll-optional-front-matter

# Prose.io
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "https://cmhelmer.com"
  media: "media"
  ignore:
    - _config.yml
  metadata:
    _posts:
      - name: "date"
        field:
          element: hidden
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "tags"
          options: "https://cmhelmer.com/data/prose/tags.jsonp"
          alterable: true
