title: From the Field Desk
description: "Personal website of C. M. Helmer re: missiology, technology, bibliology."
author:
  name: C. M. Helmer
  email: desk@cmhelmer.com
  github: cmhelmr
  twitter: cmhelmr
#  linkedin: 
#  facebook: 
  microblog: cmhelmr
#  googleplus: 

url: https://cmhelmer.com

# analytics: UA-XXXXX-Y

# See https://developers.google.com/maps/documentation/static-maps/
google_static_maps: AIzaSyC4L16R7aBCbJcmz4ukMpMKwNOpK0azZ4Y

# See https://en.m.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Kolkata

date_format: "%b %-d, %Y"

title_separator: "/"

excerpt_separator: "\n\n"

excerpt_length: 140

content_filters:
- wiki
- mark
- figure

permalink: /:slug

include: ["_pages"]

# Jekyll v3.7
# collections_dir: _collections

collections:
  notes:
    title: "Notes"
    order: 1
    output: true
    permalink: /:slug
  ctbp:
    title: "CTBP"
    order: 2
    output: true
    permalink: /:slug
  lifted:
    title: "Lifted"
    order: 3
    output: true
    permalink: /:slug
  nepali:
    title: "Nepali"
    order: 4
    output: true
    permalink: /:slug
  crossroads:
    title: "Crossroads"
    order: 5
    output: true
    permalink: /:slug

defaults:
- scope:
    path: "media"
  values:
    attachment: true # show these static files in attachments layout (default to false)
- scope:
    path: "_notes"
  values:
    layout: note
- scope:
    path: "_ctbp"
  values:
    layout: note
- scope:
    path: "_lifted"
  values:
    layout: note
- scope:
    path: "_nepali"
  values:
    layout: note
- scope:
    path: "_crossroads"
  values:
    layout: note
# Jekyll v3.7
# - scope:
#     path: "*/index.html"
#   values:
#     layout: "contents"
# - scope:
#     path: "*/tags.html"
#   values:
#     layout: "tags"
# - scope:
#     path: "*/feed.xml"
#   values:
#     layout: "feed"

sass:
  style: compressed

kramdown:
  parse_block_html: true

# Plugins:

# Not jekyll-feed plugin
# Adds link to feed in header meta
# Title is prefaced by site.title
feed:
- title: ""
  url: /feed.xml
- title: "Micro Blog"
  url: /posts/feed.xml

# Not jekyll-seo-tag plugin
# Adds to header meta
# Add name and content according to each search engine requirements for meta tags
verifications:
- name: "msvalidate.01"
  content: "623ED864F6E47AE258E006DCC84DB67D"
# - name: "alexaVerifyID"
#   content: ""
# - name: "baidu-site-verification"
#   content: ""
# - name: "google-site-verification"
#   content: ""
# - name: "yandex-verification"
#   content: ""

# jekyll-titles-from-headings:
titles_from_headings:
  strip_title: true
  collections: true

plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-default-layout
- jekyll-titles-from-headings
# - jemoji
# - jekyll-feed
# - jekyll-seo-tag
# - jekyll-paginate
# - jekyll-optional-front-matter

# Prose.io
# https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  siteurl: "https://cmhelmer.com"
  media: "media"
  ignore:
    - _config.yml
  metadata:
    _posts:
      - name: "date"
        field:
          element: hidden
          value: CURRENT_DATETIME
      - name: "tags"
        field:
          element: "multiselect"
          label: "tags"
          options: "https://cmhelmer.com/data/prose/tags.jsonp"
          alterable: true
